// 🤖 THIS FILE IS AUTO-GENERATED BY VITE PLUGIN
// Do not edit manually - changes will be overwritten
// Generated at: 10/7/2025, 11:13:56 AM

import React from "react";
import AnalyticsPage from "@/pages/admin/AnalyticsPage";
import Customers from "@/pages/admin/Customers";
import Dashboard from "@/pages/admin/Dashboard";
import FullyAutomated from "@/pages/admin/FullyAutomated";
import Inventory from "@/pages/admin/Inventory";
import Login from "@/pages/admin/Login";
import OrdersPage from "@/pages/admin/OrdersPage";
import ProductsPage from "@/pages/admin/ProductsPage";
import ProfileSettings from "@/pages/admin/ProfileSettings";
import RealTimeTest from "@/pages/admin/RealTimeTest";
import ReportsPage from "@/pages/admin/ReportsPage";
import SettingsPage from "@/pages/admin/SettingsPage";
import TransactionsPage from "@/pages/admin/TransactionsPage";
import UserManagement from "@/pages/admin/UserManagement";
import UsersPage from "@/pages/admin/UsersPage";
import BookingPage from "@/pages/user/BookingPage";
import TestAutoExport from "@/pages/user/TestAutoExport";
import UserLandingPage from "@/pages/user/UserLandingPage";

export interface RouteConfig {
  path: string;
  element: React.ReactElement;
}

// Admin routes (nested under /admin)
export const adminRoutes: RouteConfig[] = [
  { path: "analytics", element: <AnalyticsPage /> },
  { path: "customers", element: <Customers /> },
  { path: "dashboard", element: <Dashboard /> },
  { path: "fully-automated", element: <FullyAutomated /> },
  { path: "inventory", element: <Inventory /> },
  { path: "login", element: <Login /> },
  { path: "orders", element: <OrdersPage /> },
  { path: "products", element: <ProductsPage /> },
  { path: "profile-settings", element: <ProfileSettings /> },
  { path: "real-time-test", element: <RealTimeTest /> },
  { path: "reports", element: <ReportsPage /> },
  { path: "settings", element: <SettingsPage /> },
  { path: "transactions", element: <TransactionsPage /> },
  { path: "user-management", element: <UserManagement /> },
  { path: "users", element: <UsersPage /> },
];

// User routes (top-level)
export const userRoutes: RouteConfig[] = [
  { path: "/booking", element: <BookingPage /> },
  { path: "/test-auto-export", element: <TestAutoExport /> },
  { path: "/user-landing", element: <UserLandingPage /> },
];

// Total routes: 18
// Admin: 15 | User: 3

// Helper function to build full admin route paths
export const buildAdminPath = (path: string) => `/admin/${path}`;

// Export paths as constants for use in other files
export const GENERATED_PATHS = {
  // Admin routes
  ANALYTICS_PAGE: buildAdminPath("analytics"),
  CUSTOMERS: buildAdminPath("customers"),
  DASHBOARD: buildAdminPath("dashboard"),
  FULLY_AUTOMATED: buildAdminPath("fully-automated"),
  INVENTORY: buildAdminPath("inventory"),
  LOGIN: buildAdminPath("login"),
  ORDERS_PAGE: buildAdminPath("orders"),
  PRODUCTS_PAGE: buildAdminPath("products"),
  PROFILE_SETTINGS: buildAdminPath("profile-settings"),
  REAL_TIME_TEST: buildAdminPath("real-time-test"),
  REPORTS_PAGE: buildAdminPath("reports"),
  SETTINGS_PAGE: buildAdminPath("settings"),
  TRANSACTIONS_PAGE: buildAdminPath("transactions"),
  USER_MANAGEMENT: buildAdminPath("user-management"),
  USERS_PAGE: buildAdminPath("users"),

  // User routes
  BOOKING_PAGE: "/booking",
  TEST_AUTO_EXPORT: "/test-auto-export",
  USER_LANDING_PAGE: "/user-landing",
} as const;
